micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pix}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${DB_PASSWORD:password}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
